apiVersion: v1
kind: Service
metadata:
  name: alerts-ui
  namespace: mec-accelerator
spec:
  ports:
  - protocol: TCP
    port: 88
    targetPort: 80
  selector:
    app: alerts-ui
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-ui
  namespace: mec-accelerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerts-ui
  template:
    metadata:
      labels:
        app: alerts-ui
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "alerts-ui"
        dapr.io/port: "80"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: alerts-ui
        image: mecsolutionaccelerator/alerts-ui:1.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        # - containerPort: 443
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://+:80
        # volumeMounts:
        # - name: secrets
        #   mountPath: /root/.microsoft/usersecrets
