apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frame-splitter-set
  namespace: mec-accelerator
spec:
  serviceName: frame-splitter-service
  selector:
    matchLabels:
        app: frame-splitter
  replicas: 1
  template:
    metadata:
      labels:
        app: frame-splitter
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frame-splitter"
        dapr.io/app-protocol: "grpc"
        # dapr.io/app-port: "50052"
        dapr.io/log-level: "debug"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: frame-splitter
        image: mecsolutionaccelerator/framesplitter:0.1
        ports:
        - containerPort: 50052
        imagePullPolicy: IfNotPresent
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: FEEDS
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: feeds
          - name: TIMEOUT
            value: "15"
          - name : MINIOURL
            value: "http://minio.mec-accelerator.svc.cluster.local:9000"