apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: solution-accelerator-mec
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
    - name: url
      value: "tcp://admin:public@mosquitto:1883"
    - name: qos
      value: 1
    - name: retain
      value: "false"
    - name: cleanSession
      value: "true"
    - name: backoffMaxRetries
      value: "0"